version: '3.8'
services:
  pet-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: petDB
      POSTGRES_PASSWORD: petPassword123
      POSTGRES_DB: pet
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
